version: "3"
services:
  server:
    image: backend
    ports:
      - "8081:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/order_db?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=sa
      - MYSQL_DATABASE=order_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=sa

networks:
  springmysql-net: